### ISSUE TITLE
Error in the textures in Malum 1.20.1

### ISSUE THREAD

**Issue by 0Trinster0** [SammySemicolon/Malum-Mod#241]
Hello, it's me again hehe; I comment that there are certain errors in the textures in the trees of Malum, I do not know if it's because I have the graphics in fast, but it looks something wrong as you can see in the images; there are also visual errors in the main toolbar of the inventory, at the time that the item with a halo of light as the souls, the music disk, the enhanced arcane encyclopedia or other item with the nice texture that surrounds it; there are also differences in these errors, as the threshold spirit and the music disk unlike the normal spirtus and the enhanced book, you will see the differences in the images.

![2024-06-20_11 09 39](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/a717977e-eadb-4c82-9c06-3bc3840663a9)
![2024-06-20_11 09 43](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/d46d3d05-db02-4928-98cc-607121dd703d)
![2024-06-20_11 09 48](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/8f120804-c43f-46b8-9f60-b928dbef793a)
![2024-06-20_11 06 12](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/c16a8601-9c0a-4110-bb01-cf89ce4f
![2024-06-20_11 06 27](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/401e54b7-fe3b-4f62-8e44-cabffbcce016)
e674)

![2024-06-20_11 06 22](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/a9a1e61d-4bd9-4d78-88b6-3b4397f642bc)
![2024-06-20_11 06 33](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/270032cb-9707-4814-8170-42982c4d55db)
![2024-06-20_11 06 27_3](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/0d410171-abdf-4998-865d-c3b078a68886)
![2024-06-20_11 06 12](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/95efa85a-bc8b-4123-927b-4ceba807d3c7)

**Comment by utterlynowhere** [comment]
as per experience, this is caused by immediatelyfast.

**Comment by 0Trinster0** [comment]
any way to fix it without removing immediatelyfast? in 1.19.2, malum doesn't have this problem with malum in conjunction with immediatelyfast

**Comment by MFNmodding** [comment]
I have the first problem, but i don't have Immediatelyfast.

**Comment by SammySemicolon** [comment]
Fixed the leaf thing, screen particles will still be weird.

**Comment by 0Trinster0** [comment]
I just updated it, but I still have the visual bug of the black sheets, changing my quality to fancy graphics, it looks without the black border, but I have to play it on fast for my performance to be decent :(
![2024-06-20_23 29 03_2](https://github.com/SammySemicolon/Malum-Mod/assets/150207340/7e9f256c-035e-471b-9c1c-890cdb561998)

**Comment by SammySemicolon** [comment]
Do you have any other mods that might change how the leaves render by chance?

**Comment by SammySemicolon** [comment]
![image](https://github.com/SammySemicolon/Malum-Mod/assets/69329424/26a8156e-fa90-4321-b75e-57838ecc81a9)
Here's a screenshot I just took in the dev build on fast graphics

**Comment by CelestialAbyss** [comment]
> any way to fix it without removing immediatelyfast? in 1.19.2, malum doesn't have this problem with malum in conjunction with immediatelyfast

Solution is to disable `hud_batching` in ImmediatelyFast's config for the weird GUI issues. As for the unusual rendering for leaf blocks... unsure

See: https://github.com/RaphiMC/ImmediatelyFast/issues/233#issuecomment-2178566360

**Comment by 0Trinster0** [comment]
the problem is with the embeddium mod, I left only the two mods and the problem of the leaves persists, it has the option of fast tree leaves graphics:/

**Comment by MFNmodding** [comment]
[VanillaTweaks_r171632.zip](https://github.com/user-attachments/files/15942791/VanillaTweaks_r171632.zip)

Perhaps see if this messes with it, It's the Vanilla Tweaks nicer fast leaves resource pack smidgeon.
